### ISSUE TITLE
Missing manifest

### ISSUE THREAD

**Issue by lishid** [anstosa/format-hotkeys-obsidian#2]
Seems like you're missing the file manifest.json in your repo which is causing obsidian to fail to install the plugin.

**Comment by anstosa** [comment]
Oh shoot, I thought Obsidian would use the manifest in the release so I have it as a built artifact (source is in src/ and it's built to dist/ after templating in a bunch of fields from package.json to avoid repetition)

Do main.js and style.css also have to get built to the root level?

**Comment by lishid** [comment]
No, you just need a copy of the manifest in the repo's main/master branch so we can find the appropriate release tag.

This might help: https://github.com/obsidianmd/obsidian-releases#how-community-plugins-are-pulled

**Comment by anstosa** [comment]
Fixed! Thanks for the docs. updated to `manifest.json` compiles to root instead of `dist/`
