### ISSUE TITLE
Cursor position wrong after adding header on empty line

### ISSUE THREAD

**Issue by pjeby** [anstosa/format-hotkeys-obsidian#7]
When modifying an empty line to have a prefix (e.g. a heading), the cursor is placed at the beginning of the new line, instead of the end, as is done on non-empty lines.  It appears to be a problem with this logic: https://github.com/anstosa/format-hotkeys-obsidian/blob/0214ffb167046009d1d3b3f2410d8122cf03788b/src/lib/codemirror.ts#L72-L78

It should probably be checking `if (typeof content === "string" && updatedContent === "string")` instead, as the current condition will fail if either the original or replacement content is an empty string.

**Comment by anstosa** [comment]
Fixed! Thanks for reporting

**Comment by pjeby** [comment]
Awesome!  Thanks for making this.  I'm a big Typora user and I was missing being able to use ctrl-number to set heading levels, and now it works when I'm starting a new one, too.
