### ISSUE TITLE
Ctrl-Y

### ISSUE THREAD

**Issue by KarelWintersky** [anstosa/format-hotkeys-obsidian#8]
Hi! 

Please, implement "Ctrl-Y" for delete current line under cursor.

**Comment by anstosa** [comment]
Sorry, not a formatting hotkey, not in Google Docs, and much more commonly used as redo.

**Comment by KarelWintersky** [comment]
`Ctrl-Z` for redo?

**Comment by anstosa** [comment]
ctrl+z for undo, ctrl+y for redo is the standard on Windows https://en.m.wikipedia.org/wiki/Undo#:~:text=In%20most%20Microsoft%20Windows%20applications,or%20Ctrl%2BShift%2BZ.

**Comment by KarelWintersky** [comment]
Really? Never used native window hotkeys. 

Ok. May be you know, how I can delete single line from obsidian editor, using JS code?

**Comment by anstosa** [comment]
I use the vim keybindings in Obsidian, so `dd` in command mode deletes the current line.

Obsidian uses Codemirror under the hood. The following works from the console to remove the current line:
```
const codemirror = window.app.workspace.activeLeaf?.view?.editor?.cm;
const line = codemirror.getCursor("from")?.line;
codemirror.replaceRange("", {line, ch: 0}, {line: line + 1, ch: 0});
```
NB: This has no error checking so will fail if there is no cursor, or the current leaf is not a markdown view, etc.
